### ISSUE TITLE
Atom.Object.defineProperty.get is deprecated.

### ISSUE THREAD

**Issue by tungv** [minodisk/refactor#19]
atom.workspaceView is no longer available.
In most cases you will not need the view. See the Workspace docs for
alternatives: https://atom.io/docs/api/latest/Workspace.
If you do need the view, please use `atom.views.getView(atom.workspace)`,
which returns an HTMLElement.
```
Atom.Object.defineProperty.get (/Users/tung/Downloads/Atom.app/Contents/Resources/app/src/atom.js:54:11)
Main.activate (/Users/tung/.atom/packages/refactor/lib/refactor.coffee:25:9)
```

**Comment by minodisk** [comment]
See #30
