### ISSUE TITLE
support for showing choice of multiple available refactorings

### ISSUE THREAD

**Issue by jokeyrhyme** [minodisk/refactor#2]
When multiple refactorings are available for a given unit of code, it will make sense to offer these choices to the user, perhaps as a list (similar to autocomplete?).

For example:

```javascript
if (typeof value === 'string' && value.indexOf('foo') !== -1) {
  /* ... */
}
```

If the cursor is in either `'string'` or `'foo'`, available refactorings might (eventually) include:
- change from single-quote to double-quote
- change from single-quote to grave (ES6 string interpolation)
- split `&&` into nested `if` statements
- extract literal value to new constant / variable

**Comment by minodisk** [comment]
See #30
