### ISSUE TITLE
This package is unpublished from apm now

### ISSUE THREAD

**Issue by minodisk** [minodisk/refactor#30]
Can anyone take over the development of this package?

**Comment by minodisk** [comment]
[minodisk/coffee-refactor](https://github.com/minodisk/coffee-refactor/issues/new) and [minodisk/js-refactor](https://github.com/minodisk/coffee-refactor/issues/new) need new maintainers, too.

**Comment by hax** [comment]
Could you try to republish the packages?
I tried `apm publish minor` on both packages, but obviously I don't have the permissions to add release tags to your repos :sweat_smile:

**Comment by minodisk** [comment]
@hax 

Thanks for your PR.
But I'm not using Atom now...

Can you publish it in your forked repository with changing `package.json`?

```
{
  ...
  "repository": "https://github.com/hax/refactor",
  ...
}
```

The namespace `refactor`, `js-refactor`, `coffee-refactor` in Atom packages are free now.

**Comment by hax** [comment]
I republished `refactor` but failed to republish `js-refactor`, have no idea why...

**Comment by hax** [comment]
It seems `js-refactor` still use your repo so that other can not republish it...

**Comment by minodisk** [comment]
@hax Nice :wink:

I have unpublished js-refactor now. Plz retry!

https://atom.io/packages/js-refactor

**Comment by hax** [comment]
Seems ok now

**Comment by minodisk** [comment]
:+1:

**Comment by minodisk** [comment]
I'm continuously looking for a maintainer for [coffee-refactor](https://github.com/minodisk/coffee-refactor).
If someone want to publish to apm, tell me that please.

**Comment by kankaristo** [comment]
@minodisk, @hax: Could you transfer ownership of the repository, instead of using a fork? Or perhaps adding @hax as an owner on this repo?

Forked repositories don't have support for issues, and it's difficult to report issues in one repo and send pull requests to another repo.

**Comment by nemoDreamer** [comment]
Transferring ownership would have been wiser, as the fork can't have its own issues... So the "Report an Issue" button from Atom editor goes to a 404 :panda_face:

**Comment by hax** [comment]
@nemoDreamer 
Sorry, I didn't notice that the fork repo not have the issues by default.
I've set it now: https://github.com/hax/refactor/issues/

**Comment by nemoDreamer** [comment]
Oh cool! I thought that wasn't an option!
